from _typeshed import Incomplete

__all__ = ['random_string', 'random_alphanumeric']

r: Incomplete

def random_lower_string(length): ...
def random_string(length): ...
def random_bytes(length): ...
def random_alphanumeric(length): ...
def random_digits(num): ...