from _typeshed import Incomplete
from typing import Any
from io import StringIO
from docassemble.base.config import daconfig as daconfig
from docassemble.base.filter import audio_control as audio_control, get_audio_urls as get_audio_urls, get_icon_html as get_icon_html, get_video_urls as get_video_urls, markdown_to_html as markdown_to_html, my_escape as my_escape, noquote as noquote, process_target as process_target, to_text as to_text, video_control as video_control
from docassemble.base.functions import comma_and_list as comma_and_list, custom_types as custom_types, get_currency_symbol as get_currency_symbol, get_locale as get_locale, server as server, word as word
from docassemble.base.logger import logmessage as logmessage
from docassemble.base.parse import Question as Question
from docassemble.base.util import format_date as format_date, format_datetime as format_datetime, format_time as format_time
from html.parser import HTMLParser

# NOTE(allowlist):
# This is present in the allow list because the daconfig isn't loaded,
# but is assumed to be. So there's a `KeyError` on `button colors` when
# defining module level variables.

equals_byte: bytes
NoneType: type 
STRICT_MODE: bool
DECORATION_SIZE: float
DECORATION_UNITS: str
BUTTON_ICON_SIZE: float
BUTTON_ICON_UNITS: str
BUTTON_CLASS: str
BUTTON_STYLE: str
BUTTON_COLOR: str
BUTTON_COLOR_YES: str
BUTTON_COLOR_NO: str
BUTTON_COLOR_MAYBE: str
BUTTON_COLOR_CLEAR: str
BUTTON_COLOR_BACK: str
BUTTON_COLOR_REGISTER: str
BUTTON_COLOR_NEW_SESSION: str
BUTTON_COLOR_LEAVE: str
BUTTON_COLOR_URL: str
BUTTON_COLOR_RESTART: str
BUTTON_COLOR_REFRESH: str
BUTTON_COLOR_SIGNIN: str
BUTTON_COLOR_EXIT: str
BUTTON_COLOR_LOGOUT: str
BUTTON_COLOR_SEND: str
BUTTON_COLOR_DOWNLOAD: str
BUTTON_COLOR_REVIEW: str
BUTTON_COLOR_ADD: str
BUTTON_COLOR_DELETE: str
BUTTON_COLOR_UNDELETE: str
BUTTON_COLOR_HELP: str
BUTTON_COLOR_QUESTION_HELP: str
BUTTON_COLOR_BACK_TO_QUESTION: str
DEFAULT_LABELAUTY_COLOR: str
DEFAULT_LABELAUTY_NOTA_COLOR: str
DEFAULT_LABELAUTY_AOTA_COLOR: str

def process_help(help_section: dict[str, Any], status, full_page: bool = ...) -> str: ...
def tracker_tag(status) -> str: ...
def datatype_tag(datatypes) -> str: ...
def varname_tag(varnames) -> str: ...
def icon_html(status, name, width_value: float = ..., width_units: str = ...): ...
def get_choices_with_abb(status, field, the_user_dict, terms: dict | None = ..., links: list | None = ...): ...

sms_bad_words: Incomplete

def try_to_abbreviate(label, flabel, data: dict, length: int): ...
def as_sms(status, the_user_dict, links: list | None = ..., menu_items: list | None = ...): ...
def embed_input(status, variable: str): ...
def help_wrap(content, helptext, status): ...
def as_html(status, debug, root, validation_rules, field_error, the_progress_bar, steps): ...
def add_validation(extra_scripts, validation_rules, field_error) -> None: ...
def locale_format_string(the_value): ...
def double_to_single_newline(text): ...
def is_in_checkbox(field, defaultvalue, pair) -> bool: ...
def input_for(status, field, wide: bool = ..., embedded: bool = ..., floating_label: Incomplete | None = ...): ...
def myb64doublequote(text: str) -> str: ...
def myb64quote(text: str) -> str: ...
def repad(text): ...
def indent_by(text, num: int) -> str: ...
def safeid(text: str) -> str: ...
def from_safeid(text: str) -> str: ...
def escape_id(text: Any) -> str: ...
def do_escape_id(text: str) -> str: ...
def escape_for_jquery(text: str) -> str: ...
def myb64unquote(the_string: str) -> str: ...
def strip_quote(the_string: str) -> str: ...
def safe_html(the_string: str) -> str: ...
def the_currency_symbol(status, field): ...
def fix_double_quote(the_string: str) -> str: ...
def option_escape(the_string: str) -> str: ...

class MLStripper(HTMLParser):
    strict: bool
    convert_charrefs: bool
    text: StringIO 
    def __init__(self) -> None: ...
    def handle_data(self, data: str) -> None: ...
    def get_data(self) -> str: ...
    def error(self, message: str) -> None: ...

def strip_tags(html: str) -> str: ...
def clean_whitespace(text: str) -> str: ...
