from _typeshed import Incomplete as Incomplete

class MakoException(Exception): ...
class RuntimeException(MakoException): ...

class CompileException(MakoException):
    lineno: Incomplete
    pos: Incomplete
    filename: Incomplete
    source: Incomplete
    def __init__(self, message, source, lineno, pos, filename) -> None: ...

class SyntaxException(MakoException):
    lineno: Incomplete
    pos: Incomplete
    filename: Incomplete
    source: Incomplete
    def __init__(self, message, source, lineno, pos, filename) -> None: ...

class UnsupportedError(MakoException): ...
class NameConflictError(MakoException): ...
class TemplateLookupException(MakoException): ...
class TopLevelLookupException(TemplateLookupException): ...

class RichTraceback:
    error: Incomplete
    records: Incomplete
    source: Incomplete
    lineno: Incomplete
    def __init__(self, error: Union[Incomplete, None] = ..., traceback: Union[Incomplete, None] = ...) -> None: ...
    @property
    def errorname(self) -> None: ...
    @property
    def traceback(self) -> None: ...
    @property
    def reverse_records(self) -> None: ...
    @property
    def reverse_traceback(self) -> None: ...

def text_error_template(lookup: Union[Incomplete, None] = ...): ...
def html_error_template() -> None: ...
