from _typeshed import Incomplete as Incomplete

class PythonPrinter:
    indent: int
    indent_detail: Incomplete
    indentstring: str
    stream: Incomplete
    lineno: int
    line_buffer: Incomplete
    in_indent_lines: bool
    source_map: Incomplete
    def __init__(self, stream) -> None: ...
    def start_source(self, lineno) -> None: ...
    def write_blanks(self, num) -> None: ...
    def write_indented_block(self, block, starting_lineno: Union[Incomplete, None] = ...) -> None: ...
    def writelines(self, *lines) -> None: ...
    def writeline(self, line) -> None: ...
    def close(self) -> None: ...

def adjust_whitespace(text) -> None: ...
