from _typeshed import Incomplete as Incomplete

dbtableprefix: Incomplete
daconfig: Incomplete
s3_config: Incomplete
S3_ENABLED: bool
gc_config: Incomplete
GC_ENABLED: bool
azure_config: Incomplete
AZURE_ENABLED: bool
hostname: Incomplete
loaded: bool
in_celery: bool
in_cron: bool
errors: Incomplete
env_messages: Incomplete
allowed: Incomplete

def env_true_false(var) -> None: ...
def env_exists(var) -> None: ...
def env_translate(var) -> None: ...
def override_config(the_config, messages, key, var, pre_key: Union[Incomplete, None] = ...) -> None: ...
def config_error(error) -> None: ...
def cleanup_filename(filename) -> None: ...
def delete_environment() -> None: ...

this_thread: Incomplete

def aws_get_region(arn) -> None: ...
def aws_get_secret(data) -> None: ...
def azure_get_secret(data) -> None: ...
def recursive_fetch_cloud(data) -> None: ...
def fix_authorized_domain(domain) -> None: ...
def load(**kwargs) -> None: ...
def default_config() -> None: ...
def parse_redis_uri() -> None: ...
def noquote(string) -> None: ...
