from _typeshed import Incomplete as Incomplete

class GeoCoder:
    server: Incomplete
    def __init__(self, *pargs, **kwargs) -> None: ...
    data: Incomplete
    def geocode(self, *pargs, **kwargs) -> None: ...

class GoogleV3GeoCoder(GeoCoder):
    def config_ok(self) -> None: ...
    geocoder: Incomplete
    def initialize(self) -> None: ...
    def populate_address(self, address) -> None: ...

class AzureMapsGeoCoder(GeoCoder):
    def config_ok(self) -> None: ...
    geocoder: Incomplete
    def initialize(self) -> None: ...
    def populate_address(self, address) -> None: ...
