from _typeshed import Incomplete as Incomplete

html_escape: Incomplete
xml_escapes: Incomplete

def xml_escape(string) -> None: ...
def url_escape(string) -> None: ...
def trim(string) -> None: ...

class Decode:
    def __getattr__(self, key) -> None: ...

decode: Incomplete

class XMLEntityEscaper:
    codepoint2entity: Incomplete
    name2codepoint: Incomplete
    def __init__(self, codepoint2name, name2codepoint) -> None: ...
    def escape_entities(self, text) -> None: ...
    def escape(self, text) -> None: ...
    def unescape(self, text) -> None: ...

html_entities_escape: Incomplete
html_entities_unescape: Incomplete

def htmlentityreplace_errors(ex) -> None: ...

DEFAULT_ESCAPES: Incomplete
