from docassemble.base.mako.cache import CacheImpl as CacheImpl

has_beaker: bool

class BeakerCacheImpl(CacheImpl):
    def __init__(self, cache) -> None: ...
    def get_or_create(self, key, creation_function, **kw) -> None: ...
    def put(self, key, value, **kw) -> None: ...
    def get(self, key, **kw) -> None: ...
    def invalidate(self, key, **kw) -> None: ...
